### ISSUE TITLE
Clarification: Integration with git or other tools.

### ISSUE THREAD

**Issue by MinekPo1** [k4j8/filetailor#3]
I assume that to use filetailor with git you need to create a git repo of the (by default) `~/.local/share/filetailor`, this is however not clarified.

Alternatively, a closer integration with git (or other tools) could be added, by creating sub-commands which push/pull. I can implementing this, if given the go-ahead.

**Comment by k4j8** [comment]
Sorry for not seeing this until now - not sure why it wasn't in my GitHub notifications.

Yes, creating a Git repo of the folder you mentioned or some other sharing method is required to sync.

If you're still interested in integrating with Git, please let me know and I'll help the best I can.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @qinglong61, @shamemezahid, @jjitalex, @jwoo92, @icarusysuper, @hiorws, @rltbg, @schang1146, @sinapirani, @xuhdev, @Mehmetali345Dev, @lockworld, @SrgjanX, @LukeSal88, @smbpndk, @RamzyMalak, @AtlasDisease, @KriptoCihan, @ch4ot1c, @maparaschivei, @sinornis, @melvinyew, @ginccc, @Enigma1309, @evarelaavalos, @aneesh-dandime, @4mirai, @Cybergenik, @platobms, @WolfeeLuo, @faizhameed, @ibrahimcankarta, @ciaobotta, @rhyswilliamsza, @arrebagrove, @Jesus195277, @sibasish14, @captswag, @tlrib, @liuani, @Pavel-32, @AnonniX, @luciferldy, @Techout592, @thenishchalraj, @bullfrogwhackshack, @ericrswanny, @russellwmy, @DanielVenturini, @markets

**Comment by schang1146** [comment]
щ(ಠ益ಠщ)

@k4j8 can you delete ^?

Edit: Nvm, GitHub support deleted it. #rekt

**Comment by luciferldy** [comment]
已收到，谢谢
